apiVersion: apps/v1
kind: Deployment
metadata:
  name: nzxt-docs
  labels:
    app: nzxt-docs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nzxt-docs
  template:
    metadata:
      labels:
        app: nzxt-docs
    spec:
      containers:
      - name: nzxt-docs
        image: uedakojiro/nzxt-docs
        ports:
        - containerPort: 80
        env:
        - name: PORT
          value: "80"
