name: Build and Deploy

on:
  push:
    branches: [ "master" ]
permissions:
  contents: read
  packages: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Log in to the Container registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Build the Docker image
      run: docker buildx build . -f env/docker/Dockerfile --platform linux/amd64,linux/arm64  -t ghcr.io/${{ github.repository }}:latest --push
    - name: Deploy docker container
      run: "curl -m 60 http://www.nzxt-docs.tk/.webhook -H 'Authorization: Bearer ${{ secrets.ACCESS_TOKEN }}'"
